apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-portfolio-deployment
  labels:
    app: devops-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-portfolio
  template:
    metadata:
      labels:
        app: devops-portfolio
    spec:
      containers:
        - name: devops-portfolio-container
          image: rahuldeokate47666/devops-portfolio:1
          ports:
            - containerPort: 80
