apiVersion: v1
kind: Service
metadata:
  name: devops-portfolio-service
  labels:
    app: devops-portfolio
spec:
  type: LoadBalancer
  selector:
    app: devops-portfolio
  ports:
    - port: 80
      targetPort: 80
